name: test
on:
  workflow_dispatch:



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          build-checker=`expr ${{ github.run_number }} / 4`
          if [[ $build-checker -eq 4 ]];
          then
            echo "good"
            echo $build-checker
          else
            echo $build-checker
          fi